/** Declaration file generated by dts-gen */

export = puppeteer;

declare function puppeteer(...args: any[]): any;

declare namespace puppeteer {
  import EventEmitter = NodeJS.EventEmitter;
  const prototype: {};

  interface Page extends EventEmitter {
    setViewport(opts: any): void;
    goto(url: string, options?: any): Promise<any>;
    screenshot(opts: any): Promise<any>;
    evaluate(callback: any): Promise<any>;
    close(): Promise<any>;
  }

  interface Browser extends EventEmitter {
    close(): Promise<any>;
    newPage(): Page;
  }

  function connect(...args: any[]): void;

  function launch(...args: any[]): Browser;
}
